CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS TB_PERSON (
    ID          UUID DEFAULT    uuid_generate_v4(),
    NAME        VARCHAR(255)    NOT NULL,
    EMAIL       VARCHAR(255)    NOT NULL,
    CATEGORY    VARCHAR(100)    NOT NULL,
    CONSTRAINT  PERSON_ID       PRIMARY KEY(ID)
);