version: '3.7'
services:
  database:
    image: postgres:16-alpine
    container_name: postgres_user_database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=user-database